### ISSUE TITLE
Very weird issue when I scroll down

### ISSUE THREAD

**Issue by Froggy232** [RensAlthuis/vertical-overview#39] opened 2021-05-11 12:45 UTC
Hi,
First, thanks you a lot for this extension!
I have a very weird issue when I activate it, if I scroll up everything work as intended, but if I scroll down the workspace appear empty, as if the window were minimized.
I have check without any extension and with all the default settings I could check, but it doesn't change anything.
I think the issue came from my settings, as no one seems to have this problem, but I would be very curious to hear your opinion.
I have added a video to show the problem, please feel free to ask me for any other information.
Thanks you a lot!
![Capture d’écran vidéo de 11-05-2021 14 38 11](https://user-images.githubusercontent.com/72796064/117816999-70df7380-b267-11eb-88b2-5cf63c82f826.gif)

**Comment by Froggy232** [comment] 2021-05-11 13:43
Nice, so I'm not alone and the problem is not from my end!
I also use archlinux, it's very probably the same issue.

**Comment by RensAlthuis** [comment] 2021-05-11 13:53
I can reproduce this issue after switching to x11 on my laptop. Haven't found the cause yet but I'm working on it.

**Comment by Froggy232** [comment] 2021-05-11 14:00
Ok, I have the issue on wayland personally.
Thanks for your work, and for your support!

**Comment by RensAlthuis** [comment] 2021-05-11 14:51
Didn't mean to close it, but I did just push a fix. Could you guys pull the latest commit and see if that fixes it?

**Closed** 2021-05-11 15:05 UTC

**Comment by RensAlthuis** [comment] 2021-05-11 15:07
Gah, I hate that you can't turn of auto-closing issues. Anyway if you still have problems please reopen the issue

**Comment by no-comma** [comment] 2021-05-11 15:14
That fixed it for me.

**Comment by Froggy232** [comment] 2021-05-28 09:41
Hi,
Sorry for the huge delay, do you plan to update the extension on gnome-extension?
Thanks a lot for your fix!
